apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  # These keys MUST be indented one level (2 spaces) from 'spec:'
  project: default
  source:
    repoURL: https://github.com/afzie99/EKS-Real-final.git
    path: app  # Confirmed chart path
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
